services:
  - type: web
    name: amazon26
    env: php
    plan: free
    buildCommand: "echo 'No build needed'"
    startCommand: "php -S 0.0.0.0:10000 -t ."
    envVars:
      - key: APP_ENV
        value: production
    disk:
      name: disk
      mountPath: /opt/render/project/data
      sizeGB: 1
